// <auto-generated />
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations.CarsDb
{
    [DbContext(typeof(CarsDbContext))]
    partial class CarsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("Data.Entities.CarEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EngineType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("engine_type");

                    b.Property<string>("Maker")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("maker");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("owner");

                    b.Property<int>("Power")
                        .HasColumnType("INTEGER")
                        .HasColumnName("power");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("registration");

                    b.Property<int>("Volume")
                        .HasColumnType("INTEGER")
                        .HasColumnName("volume");

                    b.HasKey("Id");

                    b.ToTable("cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EngineType = "Benzyna",
                            Maker = "Seat",
                            Name = "Ibiza",
                            Owner = "Jarek",
                            Power = 130,
                            Registration = "KRA123AB",
                            Volume = 1200
                        },
                        new
                        {
                            Id = 2,
                            EngineType = "Diesel",
                            Maker = "Opel",
                            Name = "Astra",
                            Owner = "Darek",
                            Power = 180,
                            Registration = "WW123AB",
                            Volume = 1800
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
